dx | 1459 unit test cases (oclif v4)
contentstack/contentstack-apps-cli pull request #328
Opened 2024-09-30 10:39 UTC by harshithad0703

updated all test cases according to oclif v4

2024-09-30 11:00 UTC, harshithad0703 commented
I will look into the failing check

2024-10-01 04:24 UTC, aman19K commented
@cs-raj , can you pls review this PR and approve it ?

2024-10-01 09:05 UTC, cs-raj requested changes
Please use Fancy-test as we are using that in CLI

2024-10-01 10:52 UTC, cs-raj approved these changes

2024-10-01 11:05 UTC, aman19K approved these changes

2024-10-01 12:31 UTC, merged